language: java
jdk:
    - oraclejdk11
    - openjdk11

jobs:
    include:
        - stage: test
        script: ./test 1
        - # stage name not required, will continue to use `test`
        script: ./test 2
        - stage: deploy
        script: ./deploy

notifications:
    email: marcfreir@yandex.com